#pragma checksum "/home/abtuly/razor/Pages/Account/Login.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "af4696a144391ce509d87fd877c92bf60a59d348"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(razor.Pages.Account.home_abtuly_razor_Pages_Account_Login), @"mvc.1.0.razor-page", @"/home/abtuly/razor/Pages/Account/Login.cshtml")]
namespace razor.Pages.Account
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Mvc;
    using global::Microsoft.AspNetCore.Mvc.Rendering;
    using global::Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line (1,2)-(1,13) "/home/abtuly/razor/Pages/_ViewImports.cshtml"
using razor

#nullable disable
    ;
    #line default
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha1", @"af4696a144391ce509d87fd877c92bf60a59d348", @"/home/abtuly/razor/Pages/Account/Login.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha1", @"b3b0c959fd38dc6aa77992221115cd240e83b9f9", @"/home/abtuly/razor/Pages/_ViewImports.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemMetadataAttribute("Identifier", "/home/abtuly/razor/Pages/Account/Login.cshtml")]
    [global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdateAttribute]
    #nullable restore
    internal sealed class home_abtuly_razor_Pages_Account_Login : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    #nullable disable
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line (3,3)-(5,1) "/home/abtuly/razor/Pages/Account/Login.cshtml"

    ViewData["Title"] = "Login";

#line default
#line hidden
#nullable disable

            WriteLiteral("\n<h2>");
            Write(
#nullable restore
#line (7,6)-(7,23) "/home/abtuly/razor/Pages/Account/Login.cshtml"
ViewData["Title"]

#line default
#line hidden
#nullable disable
            );
            WriteLiteral(@"</h2>

<form method=""post"">
    <div class=""mb-3"">
        <label asp-for=""Input.Email"" class=""form-label""></label>
        <input asp-for=""Input.Email"" class=""form-control"" />
        <span asp-validation-for=""Input.Email"" class=""text-danger""></span>
    </div>
    <div class=""mb-3"">
        <label asp-for=""Input.Password"" class=""form-label""></label>
        <input asp-for=""Input.Password"" class=""form-control"" type=""password"" />
        <span asp-validation-for=""Input.Password"" class=""text-danger""></span>
    </div>
    <button type=""submit"" class=""btn btn-primary"">Login</button>
</form>

");
            DefineSection("Scripts", async() => {
                WriteLiteral("\n    <partial name=\"_ValidationScriptsPartial\" />\n");
            }
            );
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<LoginModel> Html { get; private set; } = default!;
        #nullable disable
        #nullable restore
public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<LoginModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<LoginModel>)PageContext?.ViewData!;
#nullable disable
        #nullable restore
public LoginModel Model => ViewData.Model!;
#nullable disable
    }
}
#pragma warning restore 1591

