#pragma checksum "/home/abtuly/razor/Pages/Attendance.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7432e03ee415d6a705a1bd74669e7afc4db2d076"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(razor.Pages.home_abtuly_razor_Pages_Attendance), @"mvc.1.0.razor-page", @"/home/abtuly/razor/Pages/Attendance.cshtml")]
namespace razor.Pages
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Mvc;
    using global::Microsoft.AspNetCore.Mvc.Rendering;
    using global::Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line (1,2)-(1,13) "/home/abtuly/razor/Pages/_ViewImports.cshtml"
using razor

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,22) "/home/abtuly/razor/Pages/Attendance.cshtml"
using razor.Entities

#nullable disable
    ;
    #line default
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha1", @"7432e03ee415d6a705a1bd74669e7afc4db2d076", @"/home/abtuly/razor/Pages/Attendance.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha1", @"b3b0c959fd38dc6aa77992221115cd240e83b9f9", @"/home/abtuly/razor/Pages/_ViewImports.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemMetadataAttribute("Identifier", "/home/abtuly/razor/Pages/Attendance.cshtml")]
    [global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdateAttribute]
    #nullable restore
    internal sealed class home_abtuly_razor_Pages_Attendance : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    #nullable disable
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\n");
#nullable restore
#line (6,3)-(8,1) "/home/abtuly/razor/Pages/Attendance.cshtml"

    ViewData["Title"] = "Attendance";

#line default
#line hidden
#nullable disable

            WriteLiteral(@"
<h2 class=""text-center"" >Attendance</h2>

<form method=""post"" class=""d-flex justify-content-around"">
    <button  class=""btn btn-primary w-25"" type=""submit"" formaction=""?handler=CheckIn"" >Check In</button>
    <button  class=""btn btn-danger w-25"" type=""submit"" formaction=""?handler=CheckOut"" >Check Out</button>
");
#nullable restore
#line (15,6)-(17,1) "/home/abtuly/razor/Pages/Attendance.cshtml"
if (Environment.IsDevelopment())
    {

#line default
#line hidden
#nullable disable

            WriteLiteral("    <button  class=\"btn btn-danger w-25\" type=\"submit\" formaction=\"?handler=ResetToday\" >Reset</button>\n");
#nullable restore
#line (18,1)-(19,1) "/home/abtuly/razor/Pages/Attendance.cshtml"
    }

#line default
#line hidden
#nullable disable

            WriteLiteral("</form>\n\n<table class=\"table mt-4\">\n    <thead>\n        <tr>\n            <th>Date</th>\n            <th>Check In</th>\n            <th>Check Out</th>\n            <th>Late?</th>\n            <th>Early Leave?</th>\n        </tr>\n    </thead>\n    <tbody>\n");
#nullable restore
#line (32,10)-(34,1) "/home/abtuly/razor/Pages/Attendance.cshtml"
foreach (var attendance in Model.UserAttendance)
        {

#line default
#line hidden
#nullable disable

            WriteLiteral("            <tr>\n                <td>");
            Write(
#nullable restore
#line (35,22)-(35,57) "/home/abtuly/razor/Pages/Attendance.cshtml"
attendance.Date.ToShortDateString()

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("</td>\n                <td>");
            Write(
#nullable restore
#line (36,22)-(36,63) "/home/abtuly/razor/Pages/Attendance.cshtml"
attendance.CheckInTime?.ToString("HH:mm")

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("</td>\n                <td>");
            Write(
#nullable restore
#line (37,22)-(37,64) "/home/abtuly/razor/Pages/Attendance.cshtml"
attendance.CheckOutTime?.ToString("HH:mm")

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("</td>\n                <td>");
            Write(
#nullable restore
#line (38,23)-(38,55) "/home/abtuly/razor/Pages/Attendance.cshtml"
attendance.IsLate ? "Yes" : "No"

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("</td>\n                <td>");
            Write(
#nullable restore
#line (39,23)-(39,61) "/home/abtuly/razor/Pages/Attendance.cshtml"
attendance.IsEarlyLeave ? "Yes" : "No"

#line default
#line hidden
#nullable disable
            );
            WriteLiteral("</td>\n            </tr>\n");
#nullable restore
#line (41,1)-(42,1) "/home/abtuly/razor/Pages/Attendance.cshtml"
        }

#line default
#line hidden
#nullable disable

            WriteLiteral("    </tbody>\n</table>\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public 
#nullable restore
#line (4,9)-(4,57) "/home/abtuly/razor/Pages/Attendance.cshtml"
Microsoft.AspNetCore.Hosting.IWebHostEnvironment

#line default
#line hidden
#nullable disable
         
#nullable restore
#line (4,58)-(4,69) "/home/abtuly/razor/Pages/Attendance.cshtml"
Environment

#line default
#line hidden
#nullable disable
         { get; private set; }
         = default!;
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<razor.Pages.AttendanceModel> Html { get; private set; } = default!;
        #nullable disable
        #nullable restore
public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<razor.Pages.AttendanceModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<razor.Pages.AttendanceModel>)PageContext?.ViewData!;
#nullable disable
        #nullable restore
public razor.Pages.AttendanceModel Model => ViewData.Model!;
#nullable disable
    }
}
#pragma warning restore 1591

